# Generated by Django 3.1.1 on 2021-05-17 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('emailid', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('photo', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Violators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='unknown', max_length=10)),
                ('pic', models.FileField(null=True, upload_to='violators/', verbose_name='')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.studentdetails')),
            ],
        ),
    ]
